### ISSUE TITLE
Loss NaN when run Qwen1.5-7B-Chat

### ISSUE THREAD

**Issue by Kahsolt** [TrustedLLM/UnKE#1]
What I do:

- modify config.py to use `Qwen1.5-7B-Chat`
- uncomment all `print` logs
- run `python unke.py` following the tutorial

What I get:

- optim-V phase seems ok
- optim-K phase gets loss nan from the 2nd step 😈

![image](https://github.com/user-attachments/assets/cbdfd605-2eeb-43ad-a6ff-2ee2a2b26baa)

What's wrong with this? Please help...

**Comment by DJC-GO-SOLO** [comment]
Thank you for your attention, I will reply to you during the day tomorrow.

**Comment by DJC-GO-SOLO** [comment]
Could you tell me which version of the transformers library you are using?

**Comment by Kahsolt** [comment]
Just returned from travel, I'm so sorry to reply a bit late. 🤧
I use `Python 3.9.0`, `numpy 1.24.1`, `torch 2.1.0` and `transformers 4.43.3`, hope these can help!

Note: even if I switched to `transformers 4.40.1` as the latest commit requires, NaN still occurs.
I run the model in `float16`, might this be the cause?

**Comment by Kahsolt** [comment]
Well, I changed `float16` to `bfloat16`, now it work perfect!
Thanks for your help, now it can be closed :)
