### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by CaiJichang212** [TrustedLLM/UnKE#2]
> Traceback (most recent call last):
>   File "/home/lyc/TNTprojectz/KE/UnKE/code/unke.py", line 365, in <module>
>     generated_ids = model.generate(
>   File "/home/lyc/miniconda3/envs/ke2torch23cu121/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/lyc/miniconda3/envs/ke2torch23cu121/lib/python3.9/site-packages/transformers/generation/utils.py", line 1622, in generate
>     result = self._sample(
>   File "/home/lyc/miniconda3/envs/ke2torch23cu121/lib/python3.9/site-packages/transformers/generation/utils.py", line 2829, in _sample
>     next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
> **RuntimeError: probability tensor contains either `inf`, `nan` or element < 0**

```python
class Config:
    # debug = False
    debug = True
    model_name = 'Meta-Llama-3-8B-Instruct'
    model_path = '/share/huggingface/Meta-Llama-3-8B-Instruct'
    # model_name = 'LLama2-7B-Chat' # 'Qwen1.5-7B-Chat' 
    # model_path = 'meta-llama/Llama-2-7b-chat-hf'#'Qwen/Qwen1.5-7B-Chat'
    keep_original_weight = True

    data_path = '../data/final_data_v2.json'
    ex_data_path = '../data/alpaca_data.json'

    lr = 2e-4
    batch_size=1
    layers = [7]
    ln_f_module= "model.norm"
    lm_head_module= "lm_head"
    layer_module_tmp = "model.layers.{}"
    #rewrite_module_tmp = "model.layers.{}.mlp.down_proj"

    device =0

    v_loss_layer = 31
    v_lr = 5e-1
    v_num_grad_steps = 25
    v_weight_decay = 1e-3
    clamp_norm_factor = 4
    optim_num_step = 50
    ex_data_num=20

    torch_dtype = torch.bfloat16
```

`python3 unke.py`

**Comment by DJC-GO-SOLO** [comment]
Thank you for your attention. Currently, this version of the code only supports LLaMA2-7B and Qwen1.5-7B. I expect to update the code to support LLaMA-3 within two days.

**Comment by CaiJichang212** [comment]
`python3 unke.py`
```python
class Config:
    # debug = False
    debug = True
    # model_name = 'Meta-Llama-3-8B-Instruct'
    # model_path = '/share/huggingface/Meta-Llama-3-8B-Instruct'
    model_name = 'LLama2-7B-Chat' # 'Qwen1.5-7B-Chat' 
    # model_path = 'meta-llama/Llama-2-7b-chat-hf'#'Qwen/Qwen1.5-7B-Chat'
    model_path = '/share/huggingface/llama-2-7b-chat-ms'
    keep_original_weight = True

    data_path = '../data/final_data_v2.json'
    ex_data_path = '../data/alpaca_data.json'

    lr = 2e-4
    batch_size=1
    layers = [7]
    ln_f_module= "model.norm"
    lm_head_module= "lm_head"
    layer_module_tmp = "model.layers.{}"
    #rewrite_module_tmp = "model.layers.{}.mlp.down_proj"

    device =0

    v_loss_layer = 31
    v_lr = 5e-1
    v_num_grad_steps = 25
    v_weight_decay = 1e-3
    clamp_norm_factor = 4
    optim_num_step = 50
    ex_data_num=20

    torch_dtype = torch.bfloat16
```
  

> File "/home/lyc/TNTprojectz/KE/UnKE/code/unke.py", line 366, in <module>
>     generated_ids = model.generate(
>   File "/home/lyc/miniconda3/envs/ke2torch23cu121/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/lyc/miniconda3/envs/ke2torch23cu121/lib/python3.9/site-packages/transformers/generation/utils.py", line 1622, in generate
>     result = self._sample(
>   File "/home/lyc/miniconda3/envs/ke2torch23cu121/lib/python3.9/site-packages/transformers/generation/utils.py", line 2829, in _sample
>     next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
> RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by CaiJichang212** [comment]
I suppose maybe reason:

> /home/lyc/miniconda3/envs/torch24py311cu121/lib/python3.11/site-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
>   warnings.warn(
> /home/lyc/miniconda3/envs/torch24py311cu121/lib/python3.11/site-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
>   warnings.warn(
> /home/lyc/miniconda3/envs/torch24py311cu121/lib/python3.11/site-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
>   warnings.warn(
> /home/lyc/miniconda3/envs/torch24py311cu121/lib/python3.11/site-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
>   warnings.warn(

**Comment by DJC-GO-SOLO** [comment]
Could you tell me which version of the transformers library you are using?

**Comment by CaiJichang212** [comment]
transformers             4.43.4

**Comment by DJC-GO-SOLO** [comment]
You need to load version 4.40.1 of the transformers library and re-download the latest unke.py code. Hopefully this will solve your problem~

**Comment by CaiJichang212** [comment]
![image](https://github.com/user-attachments/assets/2ea6050c-74f2-44d2-8c01-155d58db7d05)
![image](https://github.com/user-attachments/assets/92bec301-45f6-4bf0-ab31-24f890a2b6fc)
however the same error was raised，when edit llama2-7b-chat（qwen1.5-7b-chat is right）
> /home/bingxing2/home/scx7avs/anaconda3/envs/ke2torch23cu121/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:497: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
I suppose here is the maybe cause：
![image](https://github.com/user-attachments/assets/9dc902da-cfd9-48a2-87a6-3a8467371448)

**Comment by DJC-GO-SOLO** [comment]
These parameters work well for me. You can try setting do_sample=False. If it still doesn’t work, please send me your code. 😊😊
